name       : perl-file-sharedir
version    : 1.102
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/R/RE/REHSACK/File-ShareDir-1.102.tar.gz : 7c7334b974882587fbd9bc135f6bc04ad197abe99e6f4761953fe9ca88c57411
license    : Artistic-2.0
component  : programming.perl
summary    : Locate per-dist and per-module shared files
description: |
    Locate per-dist and per-module shared files
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
