name       : perl-file-sharedir
version    : '1.112'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/R/RE/REHSACK/File-ShareDir-1.112.tar.gz : f8305566a6e474178b0f55c3163db4d34e17c40004b5cbdacd5a5d435172dba4
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Locate per-dist and per-module shared files
description: |
    Locate per-dist and per-module shared files
builddeps  :
    - perl-class-inspector
    - perl-file-sharedir-install
    - perl-list-moreutils
rundeps    :
    - perl-class-inspector
    - perl-list-moreutils
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
