name       : perl-file-sharedir
version    : '1.104'
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/R/RE/REHSACK/File-ShareDir-1.104.tar.gz : 07b628efcdf902d6a32e6a8e084497e8593d125c03ad12ef5cc03c87c7841caf
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Locate per-dist and per-module shared files
description: |
    Locate per-dist and per-module shared files
builddeps  :
    - perl-class-inspector
rundeps    :
    - perl-class-inspector
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
