name       : perl-file-sharedir
version    : '1.116'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/R/RE/REHSACK/File-ShareDir-1.116.tar.gz : 59d90bfdf98c4656ff4173e62954ea8cf0de66565e35d108ecd7050596cb8328
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Locate per-dist and per-module shared files
description: |
    Locate per-dist and per-module shared files
builddeps  :
    - perl-class-inspector
    - perl-file-sharedir-install
    - perl-list-moreutils
    - perl-params-util
    - perl-inc-latest
rundeps    :
    - perl-class-inspector
    - perl-list-moreutils
    - perl-params-util
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
