name       : perl-file-sharedir
version    : '1.118'
release    : 11
source     :
    - https://cpan.metacpan.org/authors/id/R/RE/REHSACK/File-ShareDir-1.118.tar.gz : 3bb2a20ba35df958dc0a4f2306fc05d903d8b8c4de3c8beefce17739d281c958
homepage   : https://metacpan.org/pod/File::ShareDir
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Locate per-dist and per-module shared files
description: |
    The intent of File::ShareDir is to provide a companion to Class::Inspector and File::HomeDir, modules that take a process that is well-known by advanced Perl developers but gets a little tricky, and make it more available to the larger Perl community.
builddeps  :
    - perl-class-inspector
    - perl-file-sharedir-install
    - perl-list-moreutils
    - perl-params-util
    - perl-inc-latest
rundeps    :
    - perl-class-inspector
    - perl-list-moreutils
    - perl-params-util
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
